services:
  app:
    build: .
    container_name: tehokas-app
    ports:
      - "8000:80"
    depends_on:
      - mysql
    env_file:
      - .env

    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: tehokas-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tehokas
      MYSQL_USER: tehokas
      MYSQL_PASSWORD: tehokas123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - tehoka-db:/var/lib/mysql

volumes:
  tehoka-db:
